<?php
// Services catalogue, single source of truth for navbar, services.php and contact.php
if (!defined('SITE_NAME')) {
    require_once __DIR__ . '/config.php';
}

function slf_services() {
    return [
        [
            'slug'    => 'consultancy',
            'title'   => 'Consultancy',
            'tagline' => 'Senior-led advisory across sectors',
            'icon'    => 'bi-briefcase-fill',
            'tone'    => 'blue',
            'sector'  => 'Advisory',
            'summary' => 'Multi-sector consultancy spanning strategy, technology, social development, research and agriculture, delivered by senior practitioners.',
            'details' => [
                'overview' => 'Our consultancy practice helps governments, development partners, private companies and civil society design, implement and evaluate programs that deliver measurable impact. Each engagement is led by a senior consultant and supported by a small, accountable team with deep field experience in Tanzania and the wider East African region.',
                'deliver'  => [
                    'Strategy, organisational and HR advisory',
                    'IT strategy, software development and systems implementation',
                    'Health, education, nutrition and environmental programming',
                    'Research, baselines, evaluations and applied R&D',
                    'Agricultural advisory and field demonstrations',
                ],
                'engagements' => 'Strategic plans, theory of change, organisational reviews, MIS rollouts, sector assessments, programme evaluations, EIAs and capacity-building mandates, typically 4 to 24 weeks.',
                'audience'    => 'Government ministries and agencies, NeST-registered NGOs, bilateral and multilateral donors, foundations, and private sector firms with a sustainability mandate.',
                'outcomes'    => [
                    'Board-ready strategy documents and roadmaps',
                    'Independent, defensible evidence for decision-making',
                    'Operational systems your team can actually run',
                    'Compliance with national priorities and SDG targets',
                ],
                'why'      => 'NeST-registered, multi-sector bench, senior-led delivery, and a track record of advice that works on the ground, not just on paper.',
            ],
            'page_link'  => 'consultancy.php',
        ],
        [
            'slug'    => 'strategy',
            'title'   => 'Strategic & Business Advisory',
            'tagline' => 'Direction, structure and compliance',
            'icon'    => 'bi-compass-fill',
            'tone'    => 'blue',
            'sector'  => 'Strategy',
            'summary' => 'Long-term strategy, organisational design, HR systems and tax/regulatory compliance for resilient institutions.',
            'details' => [
                'overview' => 'We help leadership teams sharpen direction, align structure to strategy and stay financially compliant. Our advisors combine corporate and development-sector experience to produce plans that are ambitious yet executable.',
                'deliver'  => [
                    'Strategic planning and theory of change',
                    'Organisational design and change management',
                    'HR policies, recruitment and performance systems',
                    'Tax advisory and TRA-aligned compliance reviews',
                    'Board governance and risk frameworks',
                ],
                'engagements' => '5-year strategies, restructuring programmes, HR system rollouts, governance reviews, compliance audits.',
                'audience'    => 'NGOs, SMEs, social enterprises, public agencies and faith-based organisations.',
                'outcomes'    => [
                    'Clear, costed strategic roadmap',
                    'Right-sized, accountable organisation',
                    'Documented HR and governance policies',
                    'Reduced regulatory and tax exposure',
                ],
                'why'      => 'We build with you, not for you, the result is a plan your team owns and can execute on Monday morning.',
            ],
        ],
        [
            'slug'    => 'it',
            'title'   => 'Technical & IT Solutions',
            'tagline' => 'Practical technology that fits your team',
            'icon'    => 'bi-cpu-fill',
            'tone'    => 'blue',
            'sector'  => 'Technology',
            'summary' => 'Digital strategy, custom software, MIS dashboards and end-to-end systems implementation with user training.',
            'details' => [
                'overview' => 'From digital strategy to building and rolling out the system, we deliver technology that respects bandwidth realities, low-resource environments and the people who will actually use it.',
                'deliver'  => [
                    'IT strategy and infrastructure assessments',
                    'Custom web and mobile platforms',
                    'Management Information Systems and data dashboards',
                    'Integration with existing tools (ERP, CRM, donor portals)',
                    'User training, documentation and post-launch support',
                ],
                'engagements' => 'MIS builds, donor reporting dashboards, mobile data collection, internal portals, system migrations.',
                'audience'    => 'Programme teams, M&E units, finance and operations leads in NGOs, agencies and SMEs.',
                'outcomes'    => [
                    'Faster, cleaner data to leadership',
                    'Lower long-term software costs',
                    'Adoption rates that actually stick',
                    'Audit-ready data trails',
                ],
                'why'      => 'We pair engineers with sector specialists, so the system reflects how your work really happens.',
            ],
        ],
        [
            'slug'    => 'social',
            'title'   => 'Social & Development Programs',
            'tagline' => 'Health, education, nutrition and environment',
            'icon'    => 'bi-people-fill',
            'tone'    => 'yellow',
            'sector'  => 'Development',
            'summary' => 'Programme design and delivery across health, education, food security and environment, rooted in years of community work.',
            'details' => [
                'overview' => 'Our social development practice translates strategy into community-level outcomes. We design, deliver and evaluate programmes alongside the communities they serve.',
                'deliver'  => [
                    'Public health programme design and quality improvement',
                    'Curriculum reviews, school improvement and teacher training',
                    'Nutrition assessments and school-feeding programmes',
                    'Environmental Impact Assessments and climate adaptation',
                    'Natural resource and community-based conservation',
                ],
                'engagements' => 'Outreach campaigns, facility assessments, EIAs, climate adaptation strategies, school-feeding designs.',
                'audience'    => 'Ministries of Health, Education and Environment, district authorities, donors and INGOs.',
                'outcomes'    => [
                    'Measurable improvements in beneficiary indicators',
                    'Community ownership of programme results',
                    'Compliance with national and SDG frameworks',
                    'Scalable, replicable programme designs',
                ],
                'why'      => 'We measure success by what changes for people, not by the size of the report.',
            ],
        ],
        [
            'slug'    => 'research',
            'title'   => 'Research, M&E and Innovation',
            'tagline' => 'Evidence you can act on',
            'icon'    => 'bi-search',
            'tone'    => 'blue',
            'sector'  => 'Research',
            'summary' => 'Baselines, evaluations, surveys and applied R&D delivered with academic rigour and field practicality.',
            'details' => [
                'overview' => 'We design and execute research that meets donor and academic standards while remaining usable by programme teams. Our methods mix quantitative surveys, qualitative inquiry and participatory tools.',
                'deliver'  => [
                    'Baselines, midlines and end-line evaluations',
                    'Market and feasibility studies',
                    'Monitoring & Evaluation systems and frameworks',
                    'Applied R&D for development programmes',
                    'Data analysis, visualisation and policy briefs',
                ],
                'engagements' => 'Multi-country evaluations, sector studies, M&E framework design, dashboards, peer-reviewed reports.',
                'audience'    => 'Donors, INGOs, government, research institutions and impact investors.',
                'outcomes'    => [
                    'Independent, defensible evidence',
                    'Clear recommendations leadership can act on',
                    'M&E systems that survive staff turnover',
                    'Publication- and donor-ready reports',
                ],
                'why'      => 'We balance rigour with readability, findings that hold up to peer review and translate into action.',
            ],
        ],
        [
            'slug'    => 'agriculture',
            'title'   => 'Agricultural & Field Services',
            'tagline' => 'Climate-smart, value-chain ready',
            'icon'    => 'bi-tree-fill',
            'tone'    => 'yellow',
            'sector'  => 'Agriculture',
            'summary' => 'Climate-smart cultivation, agronomy advisory and demonstration plots that connect farmers, value chains and sustainability goals.',
            'details' => [
                'overview' => 'Field-level support that pairs agronomic best practice with market thinking, so farmers grow more, earn more and protect the land they depend on.',
                'deliver'  => [
                    'Climate-smart and conservation agriculture',
                    'Agronomy advisory and demonstration plots',
                    'Value chain analysis and market linkages',
                    'Post-harvest handling and storage',
                    'Cooperative and farmer-group capacity building',
                ],
                'engagements' => 'Farmer training cycles, demonstration plots, value-chain studies, cooperative strengthening.',
                'audience'    => 'Smallholder cooperatives, agribusinesses, donors and ministries of agriculture.',
                'outcomes'    => [
                    'Higher yields per hectare',
                    'Improved household incomes',
                    'Reduced post-harvest losses',
                    'Healthier soils and watersheds',
                ],
                'why'      => 'We work in the field, not from the capital, our advice survives the rainy season.',
            ],
        ],
        [
            'slug'    => 'training',
            'title'   => 'Training & Capacity Building',
            'tagline' => 'Skills that stay with your team',
            'icon'    => 'bi-mortarboard-fill',
            'tone'    => 'blue',
            'sector'  => 'Capacity',
            'summary' => 'Tailored training programmes for staff, partners and communities, from technical skills to leadership development.',
            'details' => [
                'overview' => 'We design and deliver capacity-building programmes that move beyond one-off workshops. Our approach combines learning design, on-the-job coaching and measurable competency outcomes.',
                'deliver'  => [
                    'Technical training (M&E, finance, IT, agronomy, health)',
                    'Leadership and management development',
                    'Training of Trainers (ToT) programmes',
                    'E-learning and blended curriculum design',
                    'Competency assessments and certification',
                ],
                'engagements' => 'Multi-cohort training programmes, ToT rollouts, leadership academies, e-learning builds.',
                'audience'    => 'NGO and government staff, cooperative members, community health workers, youth and women groups.',
                'outcomes'    => [
                    'Documented skills uplift across teams',
                    'Internal trainers who keep the programme alive',
                    'Higher staff retention and engagement',
                    'Verified competency for donor reporting',
                ],
                'why'      => 'We design for transfer, your team keeps the capability long after the contract ends.',
            ],
        ],
    ];
}
